spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: axel
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    hikari:
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 50
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 8080