spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    password:
    url:
    hikari:
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 50
server:
  port: 8080